name: Release
on:
  pull_request:
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Format
        uses: creyD/prettier_action@v3.1
        with:
          commit_message: "chore: Format code with Prettier"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
