name: Format
on:
  pull_request:
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Generate TOC
        run: npm run toc
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update TOC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
