name: Format
on:
  pull_request:
jobs:
  format:
    name: Format docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Generate TOC
        run: npm run toc
      - name: Commit changes
        run: |
          git config --global user.name 'Denys Dovhan'
          git config --global user.email 'denysdovhan@gmail.com'
          git commit -am "Update TOC"
          git push
